import { demoUniverse } from "@/data/demo-universe";
import { generateReport } from "@/engine/generate";
import type { EngineReport } from "@/engine/models";
import type { NeoosReport } from "@/schemas/neoos-report";

/**
 * The demo report is GENERATED by the scoring engine from the demo universe
 * of evidence records — no score here is typed by hand. Regenerating with the
 * same inputs produces byte-identical output (pinned by unit test), so the
 * demo exercises exactly the code path that imported and future live data use.
 *
 * Always labeled DEMO in the UI.
 */
const generated = generateReport(demoUniverse);

export const demoEngineReport: EngineReport = generated.engine;
export const demoReport: NeoosReport = generated.view;

/**
 * Per-section fallback content for reports that omit a workspace section.
 * Derived from the generated demo report so fallback content is engine-
 * consistent too, and labeled as demo wherever it surfaces.
 */
export const demoSections = {
  regime: demoReport.regime!,
  commentary: demoReport.commentary!,
  markets: demoReport.markets!,
  portfolio: demoReport.portfolio!,
  gold: demoReport.gold!,
  cash: demoReport.cash!,
  timeline: demoReport.timeline!,
  tiers: demoReport.tiers!,
  deploymentPlan: demoReport.deploymentPlan!,
} as const;
